build: Update deploy.yml
- 빌드 디렉토리 내 첫 번째 JAR 파일을 배포용으로 복사합니다.
- 배포를 위해 nginx.conf가 포함된 .platform 디렉토리를 복사합니다.
- 빌드 스크립트가 JDK 17을 사용하도록 설정합니다.

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -95,8 +95,10 @@ jobs:
       - name: Generate deployment package
         run: |
           mkdir -p deploy
-          if [ -f build/libs/*.jar ]; then
-            cp build/libs/*.jar deploy/application.jar
+          
+          JAR_FILE=$(find build/libs -name "*.jar" | head -n 1)
+          if [ -f "$JAR_FILE" ]; then
+            cp "$JAR_FILE" deploy/application.jar
           else
             echo "JAR file not found!"
             exit 1
@@ -116,15 +118,19 @@ jobs:
             exit 1
           fi
           
-          if [ -d .platform ]; then
-            cp -r .platform deploy/.platform
+          if [ -f .platform/nginx.conf ]; then
+            mkdir -p deploy/.platform
+            cp .platform/nginx.conf deploy/.platform/nginx.conf
           else
-            echo ".platform directory not found!"
+            echo "nginx.conf not found in .platform directory!"
             exit 1
           fi
           
           cd deploy && zip -r deploy.zip .
-        shell: bash
+        shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
+        env:
+          JAVA_HOME: /opt/hostedtoolcache/Java_Corretto_jdk/17.0.11-9.1/x64
+          JAVA_HOME_17_X64: /opt/hostedtoolcache/Java_Corretto_jdk/17.0.11-9.1/x64
 
       - name: Retrieve EB Engine Log
         run: |
