ci/cd: Fix options.json file path in deploy.yml
- options.json 파일 경로 수정
- deploy.yml 파일에서 options.json 파일 경로 수정
- deploy 폴더에 있는 options.json을 deploy/options.json으로 복사
- options.json 파일이 없을 시 에러 처리
- options.json 파일 경로를 deploy/options.json으로 수정

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -123,6 +123,13 @@ jobs:
             echo ".platform directory not found!"
             exit 1
           fi
+
+          if [ -f options.json ]; then
+            cp options.json deploy/options.json
+          else
+            echo "options.json not found!"
+            exit 1
+          fi
           
           cd deploy && zip -r deploy.zip .
         shell: bash
@@ -180,7 +187,7 @@ jobs:
             --cname-prefix piomsbe-green-$(date +%s) \
             --version-label github-action-${{steps.current-time.outputs.formattedTime}} \
             --solution-stack-name "64bit Amazon Linux 2023 v4.2.4 running Corretto 17" \
-            --option-settings file://$(pwd)/options.json
+            --option-settings file://$(pwd)/deploy/options.json
         env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
@@ -220,6 +227,26 @@ jobs:
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           AWS_DEFAULT_REGION: ap-northeast-2
 
+      - name: Wait for source environment to be terminated
+        run: |
+          echo "Waiting for source environment to be terminated..."
+          for i in {1..30}; do
+            STATUS=$(aws elasticbeanstalk describe-environments --environment-names PIOMSBE-env --query 'Environments[0].Status' --output text)
+            if [ "$STATUS" == "Terminated" ]; then
+              echo "Source environment terminated"
+              exit 0
+            else
+              echo "Source environment status: $STATUS"
+              sleep 30
+            fi
+          done
+          echo "Source environment did not terminate in time"
+          exit 1
+        env:
+          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          AWS_DEFAULT_REGION: ap-northeast-2
+
       - name: Terminate the old environment
         run: |
           aws elasticbeanstalk terminate-environment --environment-name PIOMSBE-env
@@ -250,7 +277,7 @@ jobs:
           # Extract unique user logins from comments
           UNIQUE_USERS=$(echo "$COMMENTS" | jq -r 'map(.author.login) | unique | length')
           
-          if [ $UNIQUE_USERS -lt 2 ]; then
+          if [ $UNIQUE_USERS -lt 2]; then
             echo "Not enough unique users ($UNIQUE_USERS) in the pull request comments. At least 2 unique users are required."
             exit 1
           else
